### ISSUE TITLE
Suporte para o ambiente de Sandbox

### ISSUE THREAD

**Issue by msfidelis** [pjbank/pjbank-java-sdk#51]
Seria interessante adicionar algum mecanismo de suporte para fazer requisições para o ambiente de sandbox `https://sandbox.pjbank.com.br` do PJBank. Alguma flag ou variável de ambiente que aponte para a urlbase. O que me diz @viniciusls?

**Comment by viniciusls** [comment]
@msfidelis Concordo e analisarei a melhor forma de fazer isso no momento. Obrigado por lembrar!

**Comment by msfidelis** [comment]
Vou criar essa mesma issue nos outros repos.

**Comment by viniciusls** [comment]
Já está desenvolvido. Vou fazer o merge agora :smile:

**Comment by viniciusls** [comment]
Mergeado no pull #53.

Para definir que deseja utilizar o ambiente Sandbox, basta adicionar o seguinte argumento à inicialização da JVM:
**-Dpjbank-env=dev**

**Por default, a princípio, será utilizado produção** visto que o Sandbox será utilizado em casos específicos e somente durante desenvolvimento (cujo desenvolvedor tem total acesso para adicionar em seu ambiente/JVM).

**Comment by lukaz-sampaio** [comment]
Não está funcionando pra mim. Eu já setei no projeto - uso a IDE Netbeans - , mas sempre usa a url api.pjbank.

```!shell
cd /home/lucas/NetBeansProjects/pegasus-web; -Dpjbank-env=dev JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 M2_HOME=/usr/local/apache-maven-3.6.0 /usr/local/apache-maven-3.6.0/bin/mvn -Dnetbeans.deploy=true -DskipTests=true package
```
Alguma luz?
