### ISSUE TITLE
Erro ao gerar boleto

### ISSUE THREAD

**Issue by foxpv** [pjbank/pjbank-java-sdk#71]
Bom dia!

Quando o SDK dá um post no endpoint para gerar o boleto (BoletosManager, linha 80), a API está retornando o seguinte erro:
"msg": "Specified column \"cobranca\" is not in the row"

Seria alguma alteração que houve na API?

**Comment by msfidelis** [comment]
Está utilizando ambiente de sandbox?

**Comment by foxpv** [comment]
Ambiente de produção mesmo. 
Até abri um ticket de suporte no pjbank, disseram que estão verificando. (ticket 178440).
Abri uma issue aqui pra saber se foi alguma alteração na api que deveria ser implementada no SDK.

**Comment by msfidelis** [comment]
Verifiquei com o time aqui. Consegue validar pra gente se está ok?

**Comment by foxpv** [comment]
Está ok! Eles me responderam ontem, acabei esquecendo de fechar a issue. Obrigado!
